In [5]:
import pandas as pd
df=pd.read_csv("/content/airline_passenger_satisfaction.csv")

In [7]:
df.head()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,3,5,2,5,5,5,3,5,5,Neutral or Dissatisfied
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,5,4,5,5,3,5,2,5,5,Satisfied
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,3,5,3,5,5,3,4,3,3,Satisfied
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,5,5,5,4,4,5,2,5,5,Satisfied
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,3,4,4,5,4,3,3,3,3,Satisfied

In [9]:
df.tail()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction
129875,129876,Male,28,Returning,Personal,Economy Plus,447,2,3.0,4,...,5,1,4,4,4,5,4,4,4,Neutral or Dissatisfied
129876,129877,Male,41,Returning,Personal,Economy Plus,308,0,0.0,5,...,5,2,5,2,2,4,3,2,5,Neutral or Dissatisfied
129877,129878,Male,42,Returning,Personal,Economy Plus,337,6,14.0,5,...,3,3,4,3,3,4,2,3,5,Neutral or Dissatisfied
129878,129879,Male,50,Returning,Personal,Economy Plus,337,31,22.0,4,...,4,4,5,3,3,4,5,3,5,Satisfied
129879,129880,Female,20,Returning,Personal,Economy Plus,337,0,0.0,1,...,4,2,4,2,2,2,3,2,1,Neutral or Dissatisfied

In [11]:
df.shape

(129880, 24)

In [13]:
df.columns

Index(['ID', 'Gender', 'Age', 'Customer Type', 'Type of Travel', 'Class',
       'Flight Distance', 'Departure Delay', 'Arrival Delay',
       'Departure and Arrival Time Convenience', 'Ease of Online Booking',
       'Check-in Service', 'Online Boarding', 'Gate Location',
       'On-board Service', 'Seat Comfort', 'Leg Room Service', 'Cleanliness',
       'Food and Drink', 'In-flight Service', 'In-flight Wifi Service',
       'In-flight Entertainment', 'Baggage Handling', 'Satisfaction'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 24 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   ID                                      129880 non-null  int64
 1   Gender                                  129880 non-null  object
 2   Age                                     129880 non-null  int64
 3   Customer Type                           129880 non-null  object
 4   Type of Travel                          129880 non-null  object
 5   Class                                   129880 non-null  object
 6   Flight Distance                         129880 non-null  int64
 7   Departure Delay                         129880 non-null  int64
 8   Arrival Delay                           129487 non-null  float64
 9   Departure and Arrival Time Convenience  129880 non-null  int64
 10  Ease of Online Booking                  129880 non-null  int64
 11  Check-in Service                        129880 non-null  int64
 12  Online Boarding                         129880 non-null  int64
 13  Gate Location                           129880 non-null  int64
 14  On-board Service                        129880 non-null  int64
 15  Seat Comfort                            129880 non-null  int64
 16  Leg Room Service                        129880 non-null  int64
 17  Cleanliness                             129880 non-null  int64
 18  Food and Drink                          129880 non-null  int64
 19  In-flight Service                       129880 non-null  int64
 20  In-flight Wifi Service                  129880 non-null  int64
 21  In-flight Entertainment                 129880 non-null  int64
 22  Baggage Handling                        129880 non-null  int64
 23  Satisfaction                            129880 non-null  object
dtypes: float64(1), int64(18), object(5)
memory usage: 23.8+ MB

In [17]:
df.describe()

,ID,Age,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,Ease of Online Booking,Check-in Service,Online Boarding,Gate Location,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling
count,129880.000000,129880.000000,129880.000000,129880.000000,129487.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000
mean,64940.500000,39.427957,1190.316392,14.713713,15.091129,3.057599,2.756876,3.306267,3.252633,2.976925,3.383023,3.441361,3.350878,3.286326,3.204774,3.642193,2.728696,3.358077,3.632114
std,37493.270818,15.119360,997.452477,38.071126,38.465650,1.526741,1.401740,1.266185,1.350719,1.278520,1.287099,1.319289,1.316252,1.313682,1.329933,1.176669,1.329340,1.334049,1.180025
min,1.000000,7.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,32470.750000,27.000000,414.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,3.000000
50%,64940.500000,40.000000,844.000000,0.000000,0.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,3.000000,3.000000,4.000000,3.000000,4.000000,4.000000
75%,97410.250000,51.000000,1744.000000,12.000000,13.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,5.000000
max,129880.000000,85.000000,4983.000000,1592.000000,1584.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [19]:
df["Gender"].value_counts()

Gender
Female    65899
Male      63981
Name: count, dtype: int64

In [21]:
df["Customer Type"].value_counts()

Customer Type
Returning     106100
First-time     23780
Name: count, dtype: int64

In [23]:
df["Type of Travel"].value_counts()

Type of Travel
Business    89693
Personal    40187
Name: count, dtype: int64

In [25]:
df["Class"].value_counts()

Class
Business        62160
Economy         58309
Economy Plus     9411
Name: count, dtype: int64

In [27]:
df.isnull().sum()

ID                                          0
Gender                                      0
Age                                         0
Customer Type                               0
Type of Travel                              0
Class                                       0
Flight Distance                             0
Departure Delay                             0
Arrival Delay                             393
Departure and Arrival Time Convenience      0
Ease of Online Booking                      0
Check-in Service                            0
Online Boarding                             0
Gate Location                               0
On-board Service                            0
Seat Comfort                                0
Leg Room Service                            0
Cleanliness                                 0
Food and Drink                              0
In-flight Service                           0
In-flight Wifi Service                      0
In-flight Entertainment                     0
Baggage Handling                            0
Satisfaction                                0
dtype: int64

In [29]:
df.notnull().sum()

ID                                        129880
Gender                                    129880
Age                                       129880
Customer Type                             129880
Type of Travel                            129880
Class                                     129880
Flight Distance                           129880
Departure Delay                           129880
Arrival Delay                             129487
Departure and Arrival Time Convenience    129880
Ease of Online Booking                    129880
Check-in Service                          129880
Online Boarding                           129880
Gate Location                             129880
On-board Service                          129880
Seat Comfort                              129880
Leg Room Service                          129880
Cleanliness                               129880
Food and Drink                            129880
In-flight Service                         129880
In-flight Wifi Service                    129880
In-flight Entertainment                   129880
Baggage Handling                          129880
Satisfaction                              129880
dtype: int64

In [31]:
df["Age After 5 Years"]=df["Age"]+5

In [33]:
df.head()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Age After 5 Years
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,5,2,5,5,5,3,5,5,Neutral or Dissatisfied,53
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,4,5,5,3,5,2,5,5,Satisfied,40
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,5,3,5,5,3,4,3,3,Satisfied,46
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,5,5,4,4,5,2,5,5,Satisfied,55
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,4,4,5,4,3,3,3,3,Satisfied,54

In [35]:
df[["Gender", "Age", "Class", "Age After 5 Years"]].head()

   Gender  Age     Class  Age After 5 Years
0    Male   48  Business                 53
1  Female   35  Business                 40
2    Male   41  Business                 46
3    Male   50  Business                 55
4  Female   49  Business                 54

In [37]:
df1=df.iloc[:100]
df2=df.iloc[100:200]

In [39]:
vertical_concat=pd.concat([df1,df2], ignore_index = True)
vertical_concat.head()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Age After 5 Years
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,5,2,5,5,5,3,5,5,Neutral or Dissatisfied,53
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,4,5,5,3,5,2,5,5,Satisfied,40
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,5,3,5,5,3,4,3,3,Satisfied,46
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,5,5,4,4,5,2,5,5,Satisfied,55
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,4,4,5,4,3,3,3,3,Satisfied,54

In [41]:
horizontal_concat=pd.concat([df1.reset_index(drop=True), df2.reset_index(drop=True)], axis=1)
horizontal_concat.head()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Age After 5 Years
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,4,4,3,5,4,1,4,4,Satisfied,49
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,4,5,4,2,4,3,4,4,Satisfied,56
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,5,4,5,4,4,1,4,4,Satisfied,49
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,4,4,5,3,4,3,4,4,Satisfied,47
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,5,5,4,4,5,1,5,5,Satisfied,60

In [43]:
vertical_concat.shape

(200, 25)

In [45]:
horizontal_concat.shape

(100, 50)

In [47]:
left=df[["ID", "Gender"]]
right=df[["ID", "Age"]]
merged=pd.merge(left,right,on="ID")
merged.head()

   ID  Gender  Age
0   1    Male   48
1   2  Female   35
2   3    Male   41
3   4    Male   50
4   5  Female   49

In [49]:
gender_series=df["Gender"]
gender_series.head()

0      Male
1    Female
2      Male
3      Male
4    Female
Name: Gender, dtype: object

In [52]:
s1=df["Gender"].head()
s2=df["Age"].head()
pd.concat([s1,s2], keys=["Gender","Age"])

Gender  0      Male
        1    Female
        2      Male
        3      Male
        4    Female
Age     0        48
        1        35
        2        41
        3        50
        4        49
dtype: object

In [54]:
multi_df=df.set_index(["Gender","Class"])
multi_df.head()

                 ID  Age Customer Type Type of Travel  Flight Distance  \
Gender Class
Male   Business   1   48    First-time       Business              821
Female Business   2   35     Returning       Business              821
Male   Business   3   41     Returning       Business              853
       Business   4   50     Returning       Business             1905
Female Business   5   49     Returning       Business             3470

                 Departure Delay  Arrival Delay  \
Gender Class
Male   Business                2            5.0
Female Business               26           39.0
Male   Business                0            0.0
       Business                0            0.0
Female Business                0            1.0

                 Departure and Arrival Time Convenience  \
Gender Class
Male   Business                                       3
Female Business                                       2
Male   Business                                       4
       Business                                       2
Female Business                                       3

                 Ease of Online Booking  Check-in Service  ...  Seat Comfort  \
Gender Class                                               ...
Male   Business                       3                 4  ...             5
Female Business                       2                 3  ...             4
Male   Business                       4                 4  ...             5
       Business                       2                 3  ...             5
Female Business                       3                 3  ...             4

                 Leg Room Service  Cleanliness  Food and Drink  \
Gender Class
Male   Business                 2            5               5
Female Business                 5            5               3
Male   Business                 3            5               5
       Business                 5            4               4
Female Business                 4            5               4

                 In-flight Service  In-flight Wifi Service  \
Gender Class
Male   Business                  5                       3
Female Business                  5                       2
Male   Business                  3                       4
       Business                  5                       2
Female Business                  3                       3

                 In-flight Entertainment  Baggage Handling  \
Gender Class
Male   Business                        5                 5
Female Business                        5                 5
Male   Business                        3                 3
       Business                        5                 5
Female Business                        3                 3

                            Satisfaction  Age After 5 Years
Gender Class
Male   Business  Neutral or Dissatisfied                 53
Female Business                Satisfied                 40
Male   Business                Satisfied                 46
       Business                Satisfied                 55
Female Business                Satisfied                 54

[5 rows x 23 columns]

In [56]:
df.sort_values(by="Age")

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Age After 5 Years
129783,129784,Female,7,Returning,Personal,Economy,337,0,0.0,4,...,2,3,2,2,2,5,2,2,Satisfied,12
123,124,Female,7,Returning,Personal,Economy,562,0,2.0,5,...,5,2,2,2,5,1,2,5,Neutral or Dissatisfied,12
124952,124953,Male,7,Returning,Personal,Economy Plus,728,0,29.0,4,...,5,4,5,5,1,3,5,3,Neutral or Dissatisfied,12
113695,113696,Female,7,Returning,Personal,Economy,236,70,66.0,4,...,4,5,4,4,4,3,4,5,Neutral or Dissatisfied,12
123183,123184,Male,7,Returning,Personal,Economy,468,0,12.0,4,...,4,3,4,4,4,5,4,4,Satisfied,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92779,92780,Female,85,Returning,Business,Business,171,0,0.0,2,...,4,3,4,4,4,2,5,4,Satisfied,90
44736,44737,Male,85,Returning,Business,Economy Plus,67,0,8.0,3,...,1,4,1,1,4,1,2,3,Neutral or Dissatisfied,90
70254,70255,Female,85,Returning,Business,Business,992,0,5.0,4,...,5,4,5,5,2,4,2,4,Satisfied,90
56962,56963,Male,85,First-time,Business,Economy,954,0,9.0,5,...,4,4,4,5,1,4,2,3,Neutral or Dissatisfied,90
37232,37233,Male,85,Returning,Business,Business,2078,82,76.0,1,...,4,5,4,5,4,1,3,5,Satisfied,90

In [58]:
df.sort_values(by="Flight Distance", ascending=False)

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Age After 5 Years
31815,31816,Female,45,Returning,Personal,Economy,4983,2,0.0,1,...,1,2,1,3,4,3,2,3,Neutral or Dissatisfied,50
31812,31813,Female,37,Returning,Business,Business,4983,0,2.0,3,...,4,5,4,4,3,2,3,1,Satisfied,42
31816,31817,Male,38,Returning,Business,Economy Plus,4983,2,0.0,4,...,4,3,4,4,5,4,3,5,Satisfied,43
31814,31815,Female,49,Returning,Business,Business,4983,0,14.0,1,...,4,2,4,4,4,4,2,3,Neutral or Dissatisfied,54
31811,31812,Male,42,Returning,Business,Business,4983,0,0.0,3,...,4,4,4,5,2,3,4,3,Satisfied,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30211,30212,Female,27,Returning,Personal,Economy Plus,31,8,15.0,5,...,1,5,4,4,5,3,4,4,Neutral or Dissatisfied,32
29991,29992,Female,26,First-time,Business,Economy,31,0,0.0,0,...,3,3,3,3,2,4,3,5,Neutral or Dissatisfied,31
30183,30184,Male,43,Returning,Business,Economy Plus,31,0,0.0,5,...,4,3,4,4,2,5,4,5,Satisfied,48
29862,29863,Female,53,Returning,Business,Economy,31,0,0.0,3,...,4,5,3,4,5,5,5,5,Satisfied,58
29823,29824,Female,23,First-time,Business,Economy,31,0,0.0,0,...,1,3,1,1,2,4,1,4,Satisfied,28

In [61]:
df[df["Age"]>40]

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Age After 5 Years
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,5,2,5,5,5,3,5,5,Neutral or Dissatisfied,53
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,5,3,5,5,3,4,3,3,Satisfied,46
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,5,5,4,4,5,2,5,5,Satisfied,55
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,4,4,5,4,3,3,3,3,Satisfied,54
5,6,Male,43,Returning,Business,Business,3788,0,0.0,4,...,4,4,3,3,4,4,4,4,Satisfied,48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129872,129873,Female,44,Returning,Personal,Economy Plus,308,0,22.0,4,...,4,3,5,5,3,3,3,3,Neutral or Dissatisfied,49
129874,129875,Female,55,Returning,Personal,Economy Plus,308,0,0.0,4,...,3,3,4,2,4,3,4,4,Neutral or Dissatisfied,60
129876,129877,Male,41,Returning,Personal,Economy Plus,308,0,0.0,5,...,2,5,2,2,4,3,2,5,Neutral or Dissatisfied,46
129877,129878,Male,42,Returning,Personal,Economy Plus,337,6,14.0,5,...,3,4,3,3,4,2,3,5,Neutral or Dissatisfied,47
129878,129879,Male,50,Returning,Personal,Economy Plus,337,31,22.0,4,...,4,5,3,3,4,5,3,5,Satisfied,55

In [63]:
df[df["Gender"]=="Female"]

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Age After 5 Years
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,4,5,5,3,5,2,5,5,Satisfied,40
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,4,4,5,4,3,3,3,3,Satisfied,54
7,8,Female,60,Returning,Business,Business,853,0,3.0,3,...,4,4,4,4,3,4,3,3,Satisfied,65
9,10,Female,38,Returning,Business,Business,2822,13,0.0,2,...,4,5,4,2,5,2,5,5,Satisfied,43
10,11,Female,28,First-time,Business,Business,821,0,5.0,1,...,2,5,2,2,4,1,2,3,Neutral or Dissatisfied,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129871,129872,Female,32,Returning,Business,Economy Plus,337,0,1.0,2,...,4,1,4,4,1,4,4,3,Satisfied,37
129872,129873,Female,44,Returning,Personal,Economy Plus,308,0,22.0,4,...,4,3,5,5,3,3,3,3,Neutral or Dissatisfied,49
129873,129874,Female,28,Returning,Personal,Economy Plus,337,0,0.0,2,...,3,5,3,3,4,4,3,3,Neutral or Dissatisfied,33
129874,129875,Female,55,Returning,Personal,Economy Plus,308,0,0.0,4,...,3,3,4,2,4,3,4,4,Neutral or Dissatisfied,60
129879,129880,Female,20,Returning,Personal,Economy Plus,337,0,0.0,1,...,2,4,2,2,2,3,2,1,Neutral or Dissatisfied,25

In [65]:
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [67]:
df["Class"].unique()

array(['Business', 'Economy', 'Economy Plus'], dtype=object)

In [69]:
df.nunique()

ID                                        129880
Gender                                         2
Age                                           75
Customer Type                                  2
Type of Travel                                 2
Class                                          3
Flight Distance                             3821
Departure Delay                              466
Arrival Delay                                472
Departure and Arrival Time Convenience         6
Ease of Online Booking                         6
Check-in Service                               6
Online Boarding                                6
Gate Location                                  6
On-board Service                               6
Seat Comfort                                   6
Leg Room Service                               6
Cleanliness                                    6
Food and Drink                                 6
In-flight Service                              6
In-flight Wifi Service                         6
In-flight Entertainment                        6
Baggage Handling                               5
Satisfaction                                   2
Age After 5 Years                             75
dtype: int64

In [71]:
df.duplicated().sum()

np.int64(0)

In [72]:
df.corr(numeric_only=True)

,ID,Age,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,Ease of Online Booking,Check-in Service,Online Boarding,Gate Location,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Age After 5 Years
ID,1.000000,0.020322,0.095504,-0.017643,-0.035657,-0.002192,0.013400,0.079325,0.055538,-0.000113,0.055502,0.052164,0.044088,0.024048,-0.000510,0.078793,-0.023096,0.001620,0.074569,0.020322
Age,0.020322,1.000000,0.099459,-0.009041,-0.011248,0.036960,0.022565,0.033475,0.207572,-0.000398,0.057078,0.159136,0.039119,0.052565,0.023194,-0.051347,0.016116,0.074947,-0.047991,1.000000
Flight Distance,0.095504,0.099459,1.000000,0.002402,-0.001935,-0.018914,0.065165,0.073608,0.214825,0.005520,0.111194,0.157662,0.134533,0.095648,0.057066,0.059316,0.006701,0.130507,0.064855,0.099459
Departure Delay,-0.017643,-0.009041,0.002402,1.000000,0.965291,0.000778,-0.005318,-0.018752,-0.019404,0.005973,-0.030486,-0.027999,0.014574,-0.014543,-0.029164,-0.054432,-0.015946,-0.027012,-0.004105,-0.009041
Arrival Delay,-0.035657,-0.011248,-0.001935,0.965291,1.000000,-0.000942,-0.007033,-0.021705,-0.022730,0.005658,-0.034789,-0.030521,0.011346,-0.016546,-0.031715,-0.059853,-0.017749,-0.030230,-0.007935,-0.011248
Departure and Arrival Time Convenience,-0.002192,0.036960,-0.018914,0.000778,-0.000942,1.000000,0.437620,0.091132,0.072287,0.447510,0.067297,0.008666,0.010617,0.009862,0.000687,0.072195,0.344915,-0.008380,0.070833,0.036960
Ease of Online Booking,0.013400,0.022565,0.065165,-0.005318,-0.007033,0.437620,1.000000,0.008819,0.404866,0.460041,0.039064,0.028561,0.109450,0.015125,0.030514,0.035373,0.714807,0.046564,0.039148,0.022565
Check-in Service,0.079325,0.033475,0.073608,-0.018752,-0.021705,0.091132,0.008819,1.000000,0.204238,-0.039353,0.244619,0.189979,0.152693,0.176658,0.085198,0.237601,0.043762,0.119554,0.234503,0.033475
Online Boarding,0.055538,0.207572,0.214825,-0.019404,-0.022730,0.072287,0.404866,0.204238,1.000000,0.002756,0.154242,0.419253,0.123225,0.329377,0.233500,0.074058,0.457445,0.283922,0.083541,0.207572
Gate Location,-0.000113,-0.000398,0.005520,0.005973,0.005658,0.447510,0.460041,-0.039353,0.002756,1.000000,-0.029019,0.002788,-0.005181,-0.005918,-0.002872,0.000310,0.338573,0.002741,0.000972,-0.000398
On-board Service,0.055502,0.057078,0.111194,-0.030486,-0.034789,0.067297,0.039064,0.244619,0.154242,-0.029019,1.000000,0.130545,0.357721,0.122084,0.057404,0.551569,0.119928,0.418574,0.520296,0.057078
Seat Comfort,0.052164,0.159136,0.157662,-0.027999,-0.030521,0.008666,0.028561,0.189979,0.419253,0.002788,0.130545,1.000000,0.104272,0.679613,0.575846,0.068842,0.121513,0.611837,0.074620,0.159136
Leg Room Service,0.044088,0.039119,0.134533,0.014574,0.011346,0.010617,0.109450,0.152693,0.123225,-0.005181,0.357721,0.104272,1.000000,0.096695,0.033173,0.369569,0.160317,0.300397,0.371455,0.039119
Cleanliness,0.024048,0.052565,0.095648,-0.014543,-0.016546,0.009862,0.015125,0.176658,0.329377,-0.005918,0.122084,0.679613,0.096695,1.000000,0.658054,0.090356,0.131300,0.692511,0.097071,0.052565
Food and Drink,-0.000510,0.023194,0.057066,-0.029164,-0.031715,0.000687,0.030514,0.085198,0.233500,-0.002872,0.057404,0.575846,0.033173,0.658054,1.000000,0.035210,0.132214,0.623461,0.035321,0.023194
In-flight Service,0.078793,-0.051347,0.059316,-0.054432,-0.059853,0.072195,0.035373,0.237601,0.074058,0.000310,0.551569,0.068842,0.369569,0.090356,0.035210,1.000000,0.110029,0.406094,0.629237,-0.051347
In-flight Wifi Service,-0.023096,0.016116,0.006701,-0.015946,-0.017749,0.344915,0.714807,0.043762,0.457445,0.338573,0.119928,0.121513,0.160317,0.131300,0.132214,0.110029,1.000000,0.207802,0.120376,0.016116
In-flight Entertainment,0.001620,0.074947,0.130507,-0.027012,-0.030230,-0.008380,0.046564,0.119554,0.283922,0.002741,0.418574,0.611837,0.300397,0.692511,0.623461,0.406094,0.207802,1.000000,0.379123,0.074947
Baggage Handling,0.074569,-0.047991,0.064855,-0.004105,-0.007935,0.070833,0.039148,0.234503,0.083541,0.000972,0.520296,0.074620,0.371455,0.097071,0.035321,0.629237,0.120376,0.379123,1.000000,-0.047991
Age After 5 Years,0.020322,1.000000,0.099459,-0.009041,-0.011248,0.036960,0.022565,0.033475,0.207572,-0.000398,0.057078,0.159136,0.039119,0.052565,0.023194,-0.051347,0.016116,0.074947,-0.047991,1.000000