In [3]:
import pandas as pd
df=pd.read_csv("/content/airline_passenger_satisfaction.csv")

In [ ]:
df.head()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,3,5,2,5,5,5,3,5,5,Neutral or Dissatisfied
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,5,4,5,5,3,5,2,5,5,Satisfied
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,3,5,3,5,5,3,4,3,3,Satisfied
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,5,5,5,4,4,5,2,5,5,Satisfied
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,3,4,4,5,4,3,3,3,3,Satisfied

In [ ]:
df.tail()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction
129875,129876,Male,28,Returning,Personal,Economy Plus,447,2,3.0,4,...,5,1,4,4,4,5,4,4,4,Neutral or Dissatisfied
129876,129877,Male,41,Returning,Personal,Economy Plus,308,0,0.0,5,...,5,2,5,2,2,4,3,2,5,Neutral or Dissatisfied
129877,129878,Male,42,Returning,Personal,Economy Plus,337,6,14.0,5,...,3,3,4,3,3,4,2,3,5,Neutral or Dissatisfied
129878,129879,Male,50,Returning,Personal,Economy Plus,337,31,22.0,4,...,4,4,5,3,3,4,5,3,5,Satisfied
129879,129880,Female,20,Returning,Personal,Economy Plus,337,0,0.0,1,...,4,2,4,2,2,2,3,2,1,Neutral or Dissatisfied

In [ ]:
df.shape

(129880, 24)

In [ ]:
df.columns

Index(['ID', 'Gender', 'Age', 'Customer Type', 'Type of Travel', 'Class',
       'Flight Distance', 'Departure Delay', 'Arrival Delay',
       'Departure and Arrival Time Convenience', 'Ease of Online Booking',
       'Check-in Service', 'Online Boarding', 'Gate Location',
       'On-board Service', 'Seat Comfort', 'Leg Room Service', 'Cleanliness',
       'Food and Drink', 'In-flight Service', 'In-flight Wifi Service',
       'In-flight Entertainment', 'Baggage Handling', 'Satisfaction'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 24 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   ID                                      129880 non-null  int64
 1   Gender                                  129880 non-null  object
 2   Age                                     129880 non-null  int64
 3   Customer Type                           129880 non-null  object
 4   Type of Travel                          129880 non-null  object
 5   Class                                   129880 non-null  object
 6   Flight Distance                         129880 non-null  int64
 7   Departure Delay                         129880 non-null  int64
 8   Arrival Delay                           129487 non-null  float64
 9   Departure and Arrival Time Convenience  129880 non-null  int64
 10  Ease of Online Booking                  129880 non-null  int64
 11  Check-in Service                        129880 non-null  int64
 12  Online Boarding                         129880 non-null  int64
 13  Gate Location                           129880 non-null  int64
 14  On-board Service                        129880 non-null  int64
 15  Seat Comfort                            129880 non-null  int64
 16  Leg Room Service                        129880 non-null  int64
 17  Cleanliness                             129880 non-null  int64
 18  Food and Drink                          129880 non-null  int64
 19  In-flight Service                       129880 non-null  int64
 20  In-flight Wifi Service                  129880 non-null  int64
 21  In-flight Entertainment                 129880 non-null  int64
 22  Baggage Handling                        129880 non-null  int64
 23  Satisfaction                            129880 non-null  object
dtypes: float64(1), int64(18), object(5)
memory usage: 23.8+ MB

In [ ]:
df.describe()

,ID,Age,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,Ease of Online Booking,Check-in Service,Online Boarding,Gate Location,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling
count,129880.000000,129880.000000,129880.000000,129880.000000,129487.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000
mean,64940.500000,39.427957,1190.316392,14.713713,15.091129,3.057599,2.756876,3.306267,3.252633,2.976925,3.383023,3.441361,3.350878,3.286326,3.204774,3.642193,2.728696,3.358077,3.632114
std,37493.270818,15.119360,997.452477,38.071126,38.465650,1.526741,1.401740,1.266185,1.350719,1.278520,1.287099,1.319289,1.316252,1.313682,1.329933,1.176669,1.329340,1.334049,1.180025
min,1.000000,7.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,32470.750000,27.000000,414.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,3.000000
50%,64940.500000,40.000000,844.000000,0.000000,0.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,3.000000,3.000000,4.000000,3.000000,4.000000,4.000000
75%,97410.250000,51.000000,1744.000000,12.000000,13.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,5.000000
max,129880.000000,85.000000,4983.000000,1592.000000,1584.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [ ]:
df["Gender"].value_counts()

Gender
Female    65899
Male      63981
Name: count, dtype: int64

In [ ]:
df["Customer Type"].value_counts()

Customer Type
Returning     106100
First-time     23780
Name: count, dtype: int64

In [ ]:
df["Type of Travel"].value_counts()

Type of Travel
Business    89693
Personal    40187
Name: count, dtype: int64

In [ ]:
df["Class"].value_counts()

Class
Business        62160
Economy         58309
Economy Plus     9411
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

ID                                          0
Gender                                      0
Age                                         0
Customer Type                               0
Type of Travel                              0
Class                                       0
Flight Distance                             0
Departure Delay                             0
Arrival Delay                             393
Departure and Arrival Time Convenience      0
Ease of Online Booking                      0
Check-in Service                            0
Online Boarding                             0
Gate Location                               0
On-board Service                            0
Seat Comfort                                0
Leg Room Service                            0
Cleanliness                                 0
Food and Drink                              0
In-flight Service                           0
In-flight Wifi Service                      0
In-flight Entertainment                     0
Baggage Handling                            0
Satisfaction                                0
dtype: int64

In [ ]:
df.notnull().sum()

ID                                        129880
Gender                                    129880
Age                                       129880
Customer Type                             129880
Type of Travel                            129880
Class                                     129880
Flight Distance                           129880
Departure Delay                           129880
Arrival Delay                             129487
Departure and Arrival Time Convenience    129880
Ease of Online Booking                    129880
Check-in Service                          129880
Online Boarding                           129880
Gate Location                             129880
On-board Service                          129880
Seat Comfort                              129880
Leg Room Service                          129880
Cleanliness                               129880
Food and Drink                            129880
In-flight Service                         129880
In-flight Wifi Service                    129880
In-flight Entertainment                   129880
Baggage Handling                          129880
Satisfaction                              129880
dtype: int64

In [ ]:
df["Age After 5 Years"]=df["Age"]+5

In [ ]:
df.head()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Age After 5 Years
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,5,2,5,5,5,3,5,5,Neutral or Dissatisfied,53
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,4,5,5,3,5,2,5,5,Satisfied,40
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,5,3,5,5,3,4,3,3,Satisfied,46
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,5,5,4,4,5,2,5,5,Satisfied,55
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,4,4,5,4,3,3,3,3,Satisfied,54

In [ ]:
df[["Gender", "Age", "Class", "Age After 5 Years"]].head()

   Gender  Age     Class  Age After 5 Years
0    Male   48  Business                 53
1  Female   35  Business                 40
2    Male   41  Business                 46
3    Male   50  Business                 55
4  Female   49  Business                 54

In [ ]:
df1=df.iloc[:100]
df2=df.iloc[100:200]

In [ ]:
vertical_concat=pd.concat([df1,df2], ignore_index = True)
vertical_concat.head()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Age After 5 Years
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,5,2,5,5,5,3,5,5,Neutral or Dissatisfied,53
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,4,5,5,3,5,2,5,5,Satisfied,40
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,5,3,5,5,3,4,3,3,Satisfied,46
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,5,5,4,4,5,2,5,5,Satisfied,55
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,4,4,5,4,3,3,3,3,Satisfied,54

In [ ]:
horizontal_concat=pd.concat([df1.reset_index(drop=True), df2.reset_index(drop=True)], axis=1)
horizontal_concat.head()

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Age After 5 Years
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,4,4,3,5,4,1,4,4,Satisfied,49
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,4,5,4,2,4,3,4,4,Satisfied,56
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,5,4,5,4,4,1,4,4,Satisfied,49
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,4,4,5,3,4,3,4,4,Satisfied,47
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,5,5,4,4,5,1,5,5,Satisfied,60

In [ ]:
vertical_concat.shape

(200, 25)

In [ ]:
horizontal_concat.shape

(100, 50)

In [ ]:
left=df[["ID", "Gender"]]
right=df[["ID", "Age"]]
merged=pd.merge(left,right,on="ID")
merged.head()

   ID  Gender  Age
0   1    Male   48
1   2  Female   35
2   3    Male   41
3   4    Male   50
4   5  Female   49

In [ ]:
gender_series=df["Gender"]
gender_series.head()

0      Male
1    Female
2      Male
3      Male
4    Female
Name: Gender, dtype: object

In [ ]:
s1=df["Gender"].head()
s2=df["Age"].head()
pd.concat([s1,s2], keys=["Gender","Age"])

Gender  0      Male
        1    Female
        2      Male
        3      Male
        4    Female
Age     0        48
        1        35
        2        41
        3        50
        4        49
dtype: object

In [ ]:
multi_df=df.set_index(["Gender","Class"])
multi_df.head()

                 ID  Age Customer Type Type of Travel  Flight Distance  \
Gender Class
Male   Business   1   48    First-time       Business              821
Female Business   2   35     Returning       Business              821
Male   Business   3   41     Returning       Business              853
       Business   4   50     Returning       Business             1905
Female Business   5   49     Returning       Business             3470

                 Departure Delay  Arrival Delay  \
Gender Class
Male   Business                2            5.0
Female Business               26           39.0
Male   Business                0            0.0
       Business                0            0.0
Female Business                0            1.0

                 Departure and Arrival Time Convenience  \
Gender Class
Male   Business                                       3
Female Business                                       2
Male   Business                                       4
       Business                                       2
Female Business                                       3

                 Ease of Online Booking  Check-in Service  ...  Seat Comfort  \
Gender Class                                               ...
Male   Business                       3                 4  ...             5
Female Business                       2                 3  ...             4
Male   Business                       4                 4  ...             5
       Business                       2                 3  ...             5
Female Business                       3                 3  ...             4

                 Leg Room Service  Cleanliness  Food and Drink  \
Gender Class
Male   Business                 2            5               5
Female Business                 5            5               3
Male   Business                 3            5               5
       Business                 5            4               4
Female Business                 4            5               4

                 In-flight Service  In-flight Wifi Service  \
Gender Class
Male   Business                  5                       3
Female Business                  5                       2
Male   Business                  3                       4
       Business                  5                       2
Female Business                  3                       3

                 In-flight Entertainment  Baggage Handling  \
Gender Class
Male   Business                        5                 5
Female Business                        5                 5
Male   Business                        3                 3
       Business                        5                 5
Female Business                        3                 3

                            Satisfaction  Age After 5 Years
Gender Class
Male   Business  Neutral or Dissatisfied                 53
Female Business                Satisfied                 40
Male   Business                Satisfied                 46
       Business                Satisfied                 55
Female Business                Satisfied                 54

[5 rows x 23 columns]

In [ ]:
df.sort_values(by="Age")

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Age After 5 Years
129783,129784,Female,7,Returning,Personal,Economy,337,0,0.0,4,...,2,3,2,2,2,5,2,2,Satisfied,12
123,124,Female,7,Returning,Personal,Economy,562,0,2.0,5,...,5,2,2,2,5,1,2,5,Neutral or Dissatisfied,12
124952,124953,Male,7,Returning,Personal,Economy Plus,728,0,29.0,4,...,5,4,5,5,1,3,5,3,Neutral or Dissatisfied,12
113695,113696,Female,7,Returning,Personal,Economy,236,70,66.0,4,...,4,5,4,4,4,3,4,5,Neutral or Dissatisfied,12
123183,123184,Male,7,Returning,Personal,Economy,468,0,12.0,4,...,4,3,4,4,4,5,4,4,Satisfied,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92779,92780,Female,85,Returning,Business,Business,171,0,0.0,2,...,4,3,4,4,4,2,5,4,Satisfied,90
44736,44737,Male,85,Returning,Business,Economy Plus,67,0,8.0,3,...,1,4,1,1,4,1,2,3,Neutral or Dissatisfied,90
70254,70255,Female,85,Returning,Business,Business,992,0,5.0,4,...,5,4,5,5,2,4,2,4,Satisfied,90
56962,56963,Male,85,First-time,Business,Economy,954,0,9.0,5,...,4,4,4,5,1,4,2,3,Neutral or Dissatisfied,90
37232,37233,Male,85,Returning,Business,Business,2078,82,76.0,1,...,4,5,4,5,4,1,3,5,Satisfied,90

In [ ]:
df.sort_values(by="Flight Distance", ascending=False)

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Age After 5 Years
31815,31816,Female,45,Returning,Personal,Economy,4983,2,0.0,1,...,1,2,1,3,4,3,2,3,Neutral or Dissatisfied,50
31812,31813,Female,37,Returning,Business,Business,4983,0,2.0,3,...,4,5,4,4,3,2,3,1,Satisfied,42
31816,31817,Male,38,Returning,Business,Economy Plus,4983,2,0.0,4,...,4,3,4,4,5,4,3,5,Satisfied,43
31814,31815,Female,49,Returning,Business,Business,4983,0,14.0,1,...,4,2,4,4,4,4,2,3,Neutral or Dissatisfied,54
31811,31812,Male,42,Returning,Business,Business,4983,0,0.0,3,...,4,4,4,5,2,3,4,3,Satisfied,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30211,30212,Female,27,Returning,Personal,Economy Plus,31,8,15.0,5,...,1,5,4,4,5,3,4,4,Neutral or Dissatisfied,32
29991,29992,Female,26,First-time,Business,Economy,31,0,0.0,0,...,3,3,3,3,2,4,3,5,Neutral or Dissatisfied,31
30183,30184,Male,43,Returning,Business,Economy Plus,31,0,0.0,5,...,4,3,4,4,2,5,4,5,Satisfied,48
29862,29863,Female,53,Returning,Business,Economy,31,0,0.0,3,...,4,5,3,4,5,5,5,5,Satisfied,58
29823,29824,Female,23,First-time,Business,Economy,31,0,0.0,0,...,1,3,1,1,2,4,1,4,Satisfied,28

In [ ]:
df[df["Age"]>40]

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Age After 5 Years
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,5,2,5,5,5,3,5,5,Neutral or Dissatisfied,53
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,5,3,5,5,3,4,3,3,Satisfied,46
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,5,5,4,4,5,2,5,5,Satisfied,55
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,4,4,5,4,3,3,3,3,Satisfied,54
5,6,Male,43,Returning,Business,Business,3788,0,0.0,4,...,4,4,3,3,4,4,4,4,Satisfied,48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129872,129873,Female,44,Returning,Personal,Economy Plus,308,0,22.0,4,...,4,3,5,5,3,3,3,3,Neutral or Dissatisfied,49
129874,129875,Female,55,Returning,Personal,Economy Plus,308,0,0.0,4,...,3,3,4,2,4,3,4,4,Neutral or Dissatisfied,60
129876,129877,Male,41,Returning,Personal,Economy Plus,308,0,0.0,5,...,2,5,2,2,4,3,2,5,Neutral or Dissatisfied,46
129877,129878,Male,42,Returning,Personal,Economy Plus,337,6,14.0,5,...,3,4,3,3,4,2,3,5,Neutral or Dissatisfied,47
129878,129879,Male,50,Returning,Personal,Economy Plus,337,31,22.0,4,...,4,5,3,3,4,5,3,5,Satisfied,55

In [ ]:
df[df["Gender"]=="Female"]

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Age After 5 Years
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,4,5,5,3,5,2,5,5,Satisfied,40
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,4,4,5,4,3,3,3,3,Satisfied,54
7,8,Female,60,Returning,Business,Business,853,0,3.0,3,...,4,4,4,4,3,4,3,3,Satisfied,65
9,10,Female,38,Returning,Business,Business,2822,13,0.0,2,...,4,5,4,2,5,2,5,5,Satisfied,43
10,11,Female,28,First-time,Business,Business,821,0,5.0,1,...,2,5,2,2,4,1,2,3,Neutral or Dissatisfied,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129871,129872,Female,32,Returning,Business,Economy Plus,337,0,1.0,2,...,4,1,4,4,1,4,4,3,Satisfied,37
129872,129873,Female,44,Returning,Personal,Economy Plus,308,0,22.0,4,...,4,3,5,5,3,3,3,3,Neutral or Dissatisfied,49
129873,129874,Female,28,Returning,Personal,Economy Plus,337,0,0.0,2,...,3,5,3,3,4,4,3,3,Neutral or Dissatisfied,33
129874,129875,Female,55,Returning,Personal,Economy Plus,308,0,0.0,4,...,3,3,4,2,4,3,4,4,Neutral or Dissatisfied,60
129879,129880,Female,20,Returning,Personal,Economy Plus,337,0,0.0,1,...,2,4,2,2,2,3,2,1,Neutral or Dissatisfied,25

In [ ]:
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
df["Class"].unique()

array(['Business', 'Economy', 'Economy Plus'], dtype=object)

In [ ]:
df.nunique()

ID                                        129880
Gender                                         2
Age                                           75
Customer Type                                  2
Type of Travel                                 2
Class                                          3
Flight Distance                             3821
Departure Delay                              466
Arrival Delay                                472
Departure and Arrival Time Convenience         6
Ease of Online Booking                         6
Check-in Service                               6
Online Boarding                                6
Gate Location                                  6
On-board Service                               6
Seat Comfort                                   6
Leg Room Service                               6
Cleanliness                                    6
Food and Drink                                 6
In-flight Service                              6
In-flight Wifi Service                         6
In-flight Entertainment                        6
Baggage Handling                               5
Satisfaction                                   2
Age After 5 Years                             75
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.corr(numeric_only=True)

In [5]:
import pandas as pd
df=pd.read_csv("/content/Bank_Churn.csv")

In [ ]:
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.tail()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.describe()

,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [ ]:
df.value_counts()

CustomerId  Surname   CreditScore  Geography  Gender  Age  Tenure  Balance    NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited
15815316    Kennedy   644          France     Male    50   9       76817.00   4              1          0               196371.13        1         1
15815295    John      662          France     Female  38   2       96479.81   1              1          0               120259.41        0         1
15815271    Ritchie   755          Germany    Male    43   6       165048.50  3              1          0               16929.41         1         1
15815259    Fang      835          France     Female  56   2       0.00       2              1          1               39820.13         0         1
15815236    Chiganu   574          Spain      Male    34   5       0.00       2              0          0               28269.86         0         1
                                                                                                                                                  ..
15565796    Docherty  745          Germany    Male    48   10      96048.55   1              1          0               74510.65         0         1
15565779    Kent      627          Germany    Female  30   6       57809.32   1              1          0               188258.49        0         1
15565714    Cattaneo  601          France     Male    47   1       64430.06   2              0          1               96517.97         0         1
15565706    Akobundu  612          Spain      Male    35   1       0.00       1              1          1               83256.26         1         1
15565701    Ferri     698          Spain      Female  39   9       161993.89  1              0          0               90212.38         0         1
Name: count, Length: 10000, dtype: int64

In [ ]:
df.head(10)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [ ]:
df.sample(5)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
2300,15647266,Y?an,651,Spain,Female,45,10,135923.16,1,1,0,18732.84,0
8082,15774551,K?,772,Spain,Male,36,3,112029.83,1,1,1,186948.35,0
4307,15702499,Schnaars,770,Spain,Male,46,9,190678.02,1,1,1,14725.36,0
7857,15621457,Chu,850,France,Male,27,6,96654.72,2,0,0,152740.16,0
2687,15679148,Oliver,508,France,Male,44,3,115451.05,2,0,0,67234.33,0

In [ ]:
df.shape

(10000, 13)

In [ ]:
df.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10000 non-null  int64
 1   Surname          10000 non-null  object
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  object
 4   Gender           10000 non-null  object
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(8), object(3)
memory usage: 1015.8+ KB

In [ ]:
df.dtypes

CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [ ]:
df["Gender"]

0       Female
1       Female
2       Female
3       Female
4       Female
         ...
9995      Male
9996      Male
9997    Female
9998      Male
9999    Female
Name: Gender, Length: 10000, dtype: object

In [ ]:
df[["Gender","Age","Tenure"]]

      Gender  Age  Tenure
0     Female   42       2
1     Female   41       1
2     Female   42       8
3     Female   39       1
4     Female   43       2
...      ...  ...     ...
9995    Male   39       5
9996    Male   35      10
9997  Female   36       7
9998    Male   42       3
9999  Female   28       4

[10000 rows x 3 columns]

In [ ]:
df.iloc[0]

CustomerId          15634602
Surname             Hargrave
CreditScore              619
Geography             France
Gender                Female
Age                       42
Tenure                     2
Balance                  0.0
NumOfProducts              1
HasCrCard                  1
IsActiveMember             1
EstimatedSalary    101348.88
Exited                     1
Name: 0, dtype: object

In [ ]:
df.iloc[0:10]

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [ ]:
df.loc[0]

CustomerId          15634602
Surname             Hargrave
CreditScore              619
Geography             France
Gender                Female
Age                       42
Tenure                     2
Balance                  0.0
NumOfProducts              1
HasCrCard                  1
IsActiveMember             1
EstimatedSalary    101348.88
Exited                     1
Name: 0, dtype: object

In [ ]:
df.isnull()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.notnull()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,True,True,True,True,True,True,True,True,True,True,True,True,True
9996,True,True,True,True,True,True,True,True,True,True,True,True,True
9997,True,True,True,True,True,True,True,True,True,True,True,True,True
9998,True,True,True,True,True,True,True,True,True,True,True,True,True
9999,True,True,True,True,True,True,True,True,True,True,True,True,True

In [ ]:
df.notnull().sum()

CustomerId         10000
Surname            10000
CreditScore        10000
Geography          10000
Gender             10000
Age                10000
Tenure             10000
Balance            10000
NumOfProducts      10000
HasCrCard          10000
IsActiveMember     10000
EstimatedSalary    10000
Exited             10000
dtype: int64

In [ ]:
df.dropna()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.fillna(0)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df["Gender"].unique()

array(['Female', 'Male'], dtype=object)

In [ ]:
df["Gender"].nunique()

2

In [ ]:
df["Age"].value_counts()

Age
37    478
38    477
35    474
36    456
34    447
     ...
84      2
82      1
88      1
85      1
83      1
Name: count, Length: 70, dtype: int64

In [ ]:
df.sort_values(by="Age")

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1678,15569178,Kharlamov,570,France,Female,18,4,82767.42,1,1,0,71811.90,0
4556,15796231,Nwankwo,681,France,Female,18,1,98894.39,1,1,1,9596.40,0
9520,15673180,Onyekaozulu,727,Germany,Female,18,2,93816.70,2,1,0,126172.11,0
9526,15665521,Chiazagomekpele,642,Germany,Male,18,5,111183.53,2,0,1,10063.75,0
9572,15641688,Collier,644,Spain,Male,18,7,0.00,1,0,1,59645.24,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3531,15653251,Hickey,408,France,Female,84,8,87873.39,1,0,0,188484.52,1
3033,15578006,Yao,787,France,Female,85,10,0.00,2,1,1,116537.96,0
2458,15813303,Rearick,513,Spain,Male,88,10,0.00,2,1,1,52952.24,0
6443,15764927,Rogova,753,France,Male,92,3,121513.31,1,0,1,195563.99,0
6759,15660878,T'ien,705,France,Male,92,1,126076.24,2,1,1,34436.83,0

In [ ]:
df[df["Age"]>40]

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9981,15672754,Burbidge,498,Germany,Male,42,3,152039.70,1,1,1,53445.17,1
9982,15768163,Griffin,655,Germany,Female,46,7,137145.12,1,1,0,115146.40,1
9986,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9991,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9998,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1

In [ ]:
df[df["Gender"]=="Male"]

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
5,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
8,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
10,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9995,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9998,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1

In [ ]:
df["Tenure_after_2_years"]=df["Tenure"]+2

In [ ]:
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Tenure_after_2_years
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,4
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,3
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,10
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,3
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,4

In [ ]:
df.rename(columns={"Gendder":"Passenger Gender"})

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Tenure_after_2_years
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,4
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,3
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,10
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,3
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,7
9996,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,12
9997,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,9
9998,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,5
9999,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,6

In [ ]:
df.tail(2)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Tenure_after_2_years
9998,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,5
9999,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,6

In [ ]:
df.drop("Tenure_after_2_years",axis=1)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
left=df[["CustomerId","Gender"]]
right=df[["CustomerId","Age"]]
pd.merge(left,right,on="CustomerId")

      CustomerId  Gender  Age
0       15634602  Female   42
1       15647311  Female   41
2       15619304  Female   42
3       15701354  Female   39
4       15737888  Female   43
...          ...     ...  ...
9995    15606229    Male   39
9996    15569892    Male   35
9997    15584532  Female   36
9998    15682355    Male   42
9999    15628319  Female   28

[10000 rows x 3 columns]

In [ ]:
df["Age"].mean()

np.float64(38.9218)

In [ ]:
df["Age"].max()

92

In [ ]:
df["Tenure"].sum()

np.int64(50128)

In [ ]:
df["CustomerId"].min()

15565701

In [ ]:
df["Tenure"].median()

5.0

In [ ]:
df["Age"].count()

np.int64(10000)

In [6]:
df["Tenure"].std()

2.892174377049708

In [9]:
#count missing values
missing_values=df.isnull().sum()
print(missing_values)

CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [11]:
df.isnull().sum()/len(df)*100

CustomerId         0.0
Surname            0.0
CreditScore        0.0
Geography          0.0
Gender             0.0
Age                0.0
Tenure             0.0
Balance            0.0
NumOfProducts      0.0
HasCrCard          0.0
IsActiveMember     0.0
EstimatedSalary    0.0
Exited             0.0
dtype: float64

In [13]:
pd.DataFrame({"Missing Count": df.isnull().sum(), "Missing Percentage": (df.isnull().sum()/len(df))*100})

                 Missing Count  Missing Percentage
CustomerId                   0                 0.0
Surname                      0                 0.0
CreditScore                  0                 0.0
Geography                    0                 0.0
Gender                       0                 0.0
Age                          0                 0.0
Tenure                       0                 0.0
Balance                      0                 0.0
NumOfProducts                0                 0.0
HasCrCard                    0                 0.0
IsActiveMember               0                 0.0
EstimatedSalary              0                 0.0
Exited                       0                 0.0